trigger:
- none

pool: 
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: KubernetesSecretsandConfigMaps
  displayName: KubernetesSecretsandConfigMaps
  jobs:
  - deployment: KubernetesSecretsandConfigMaps
    displayName: KubernetesSecretsandConfigMaps
    environment: "dev"
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true
          - task: CmdLine@2
            inputs:
              script: |
                kubectl get secrets -n kafka --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                kubectl describe kafkausers kafka-producer -n kafka --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                kubectl describe kafkausers kafka-consumer -n kafka --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                kubectl describe secret kafka-producer -n kafka --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                kubectl describe secret kafka-consumer -n kafka --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                kubectl get secret kafka-producer -n kafka --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster -o jsonpath='{.data.user\.p12}' | base64 -d > /tmp/kafka-producer.p12
                kubectl get secret kafka-producer -o jsonpath='{.data.user\.password}' -n kafka --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster | base64 -d > /tmp/kafka-producer.password
                kubectl get secret kafka-consumer -n kafka --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster -o jsonpath='{.data.user\.p12}' | base64 -d > /tmp/kafka-consumer.p12
                kubectl get secret kafka-consumer -o jsonpath='{.data.user\.password}' -n kafka --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster | base64 -d > /tmp/kafka-consumer.password
                kubectl get secret kafka-with-kraft-cluster-ca-cert -n kafka --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster -o jsonpath='{.data.ca\.p12}' | base64 -d > /tmp/ca.p12
                kubectl get secret kafka-with-kraft-cluster-ca-cert -n kafka --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster -o jsonpath='{.data.ca\.password}' | base64 -d > /tmp/ca.password
                if [[ -z `/bin/bash -c "kubectl get configmap -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster|grep kafka-producer-app|cut -d ' ' -f1"` ]]
                then
                  kubectl create configmap kafka-producer-app --from-file=src/kafka-producer/src/main/resources/application.yml -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                else
                  kubectl delete configmap kafka-producer-app -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                  kubectl create configmap kafka-producer-app --from-file=src/kafka-producer/src/main/resources/application.yml -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                fi
                if [[ -z `/bin/bash -c "kubectl get secret -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster|grep kafka-producer-app|cut -d ' ' -f1"` ]]
                then
                  kubectl create secret generic kafka-producer-app --from-file=keystore.p12=/tmp/kafka-producer.p12 --from-file=keystore.password=/tmp/kafka-producer.password --from-file=truststore.p12=/tmp/ca.p12 --from-file=truststore.password=/tmp/ca.password -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                else
                  kubectl delete secret kafka-producer-app -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                  kubectl create secret generic kafka-producer-app --from-file=keystore.p12=/tmp/kafka-producer.p12 --from-file=keystore.password=/tmp/kafka-producer.password --from-file=truststore.p12=/tmp/ca.p12 --from-file=truststore.password=/tmp/ca.password -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster                  
                fi
                if [[ -z `/bin/bash -c "kubectl get configmap -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster|grep kafka-consumer-app|cut -d ' ' -f1"` ]]
                then
                  kubectl create configmap kafka-consumer-app --from-file=src/kafka-consumer/src/main/resources/application.yml -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                else
                  kubectl delete configmap kafka-consumer-app -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                  kubectl create configmap kafka-consumer-app --from-file=src/kafka-consumer/src/main/resources/application.yml -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster                  
                fi
                if [[ -z `/bin/bash -c "kubectl get secret -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster|grep kafka-consumer-app|cut -d ' ' -f1"` ]]
                then
                  kubectl create secret generic kafka-consumer-app --from-file=keystore.p12=/tmp/kafka-consumer.p12 --from-file=keystore.password=/tmp/kafka-consumer.password --from-file=truststore.p12=/tmp/ca.p12 --from-file=truststore.password=/tmp/ca.password -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                else
                  kubectl delete secret generic kafka-consumer-app -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster                  
                  kubectl create secret generic kafka-consumer-app --from-file=keystore.p12=/tmp/kafka-consumer.p12 --from-file=keystore.password=/tmp/kafka-consumer.password --from-file=truststore.p12=/tmp/ca.p12 --from-file=truststore.password=/tmp/ca.password -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                fi
                kubectl get configmaps -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                kubectl get secrets -n producer-consumer --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster